export const FILTER_TUTORS_BY_COURSE = "FILTER_TUTORS_BY_COURSE";
export const FILTER_TUTORS_BY_RATING = "FILTER_TUTORS_BY_RATING";
export const GET_TUTORS = "GET_TUTORS";
export const GET_COURSES = "GET_COURSES";
export const RESET_FILTERS = "RESET_FILTERS";
export const SEARCH_TUTOR = "SEARCH_TUTOR";
